version: "3.8"

services:
  web:
      container_name: "gin"
      build :
          context: ./
          dockerfile: dockerfile
      ports:  
        - 8070:8070
      tty: true

  postgres:
      container_name: postgres
      image: postgres:11-alpine3.17
      ports: 
        - 5532:5432
      env_file:
        - .env  #寫跟docker-compose.yaml 相對路徑的.env檔案
      volumes:
        - D:\temp_data:/var/lib/postgresql/data


      
      



